name = "AsympPDC"
uuid = "1669ae32-4138-484c-af98-b310d7334c94"
authors = ["Koichi Sameshima"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
